# Crear base de datos
# Sólo se ejecuta la primera vez
import sqlite3
DB_PATH = "BD/indicadores.db"



# Crear la conexión y las tablas
def crear_db():
    conex= sqlite3.connect(DB_PATH)
    cursor= conex.cursor()
    
    # Tabla de indicadores
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS indicadores (
            id INT PRIMARY KEY,
            n_abv TEXT NOT NULL UNIQUE,
            nombre TEXT NOT NULL UNIQUE,
            dimension TEXT NOT NULL,
            descripcion TEXT NOT NULL,
            unidades TEXT NOT NULL,
            uds TEXT NOT NULL,
            periodicidad TEXT NOT NULL,
            fuente TEXT NOT NULL,
            url TEXT NOT NULL,
            siSube TEXT NOT NULL,
            subeExp TEXT NOT NULL,
            siBaja TEXT NOT NULL,
            bajaExp TEXT NOT NULL  
        );
        """
    )

    # Tabla de datos de los seleccionados
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS seleccionados (
            id INT PRIMARY KEY,
            fechas TEXT NOT NULL,
            valores TEXT NOT NULL,
            FOREIGN KEY (id) REFERENCES indicadores (id) ON DELETE CASCADE ON UPDATE CASCADE
        );
        """
    )

    # Tabla de datos de los usuarios
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS usuarios (
            username TEXT NOT NULL PRIMARY KEY,
            contraseña TEXT NOT NULL,
            email TEXT NOT NULL UNIQUE
        );
        """
    )

    # Tabla de datos de los archivos de los perfiles
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS perfiles (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            nombre TEXT NOT NULL,
            fecha TEXT NOT NULL,
            usuario TEXT NOT NULL,
            indicadores TEXT NOT NULL,
            sector TEXT NOT NULL,
            tamaño TEXT NOT NULL,
            tipo TEXT NOT NULL,
            ambito TEXT NOT NULL,
            importacion TEXT NOT NULL,
            exportacion TEXT NOT NULL,
            sostenibilidad TEXT NOT NULL,
            sexo TEXT NOT NULL,
            edad TEXT NOT NULL,
            creencia TEXT NOT NULL,
            FOREIGN KEY (usuario) REFERENCES usuarios (username) ON DELETE CASCADE ON UPDATE CASCADE
        );
        """
    )

    # Tabla de datos de los archivos de los perfiles
    cursor.execute(
        """
        CREATE TABLE IF NOT EXISTS inds_perfil (
            id INT,
            perfil INT,
            fechas TEXT NOT NULL,
            valores TEXT NOT NULL,
            PRIMARY KEY (id, perfil),
            FOREIGN KEY (id) REFERENCES indicadores (id) ON DELETE CASCADE ON UPDATE CASCADE,
            FOREIGN KEY (perfil) REFERENCES perfiles (id) ON DELETE CASCADE ON UPDATE CASCADE
        );
        """
    )


    # Info de todos los indicadores
    inds= [
         (100, "Índice corrupción", 
         "Índice de percepción de la corrupción", 
         "Político", 
         "Nivel de corrupción percibido en el sector público, evaluado del 0 (nivel alto de corrupción) a 100 (nivel bajo de corrupción)", 
         "Escala de 0 (nivel alto) a 100 (nivel bajo)", 
         "0(+) / 100(-)", 
         "Anual", 
         "Datosmacro", 
         "https://datosmacro.expansion.com/estado/indice-percepcion-corrupcion/espana",
         "Positivo",
         "Disminución de la corrupción del país.",
         "Negativo",
         "Aumento de la corrupción del país."),

        (101, "Índice de fragilidad", 
         "Índice mundial de fragilidad", 
         "Político", 
         "Mide la estabilidad de un país, teniendo en cuenta diferentes factores (violencia, pobreza, gobernanza, conflictos…), evaluado del 0 (poca fragilidad) a 100 (alta fragilidad)", 
         "Escala de 0 (nivel bajo) a 100 (nivel alto)", 
         "0(-) / 100(+)", 
         "Anual", 
         "Datosmacro", 
         "https://datosmacro.expansion.com/estado/indice-mundial-fragilidad/espana",
         "Negativo",
         "Aumento de la inestabilidad del país.",
         "Positivo",
         "Disminución de la inestabilidad del país."),

        (102, "IVA general", 
         "Impuesto sobre el Valor Añadido - General", 
         "Político", 
         "Porcentaje aplicado sobre el precio de un producto y que aumenta su precio este mismo porcentaje. Se aplica a la mayoría de los productos y servicios", 
         "Porcentaje", 
         "%", 
         "Anual", 
         "Datosmacro", 
         "https://datosmacro.expansion.com/impuestos/iva/espana",
         "Negativo",
         "Aumento de la cantidad a pagar por este impuesto.",
         "Positivo",
         "Disminución la cantidad a pagar por este impuesto."),

        (103, "IVA reducido", 
         "Impuesto sobre el Valor Añadido - Reducido", 
         "Político", 
         "Porcentaje aplicado sobre el precio de un producto y que aumenta su precio este mismo porcentaje. Se aplica a ciertos productos y servicios, como alimentos o transporte", 
         "Porcentaje", 
         "%", 
         "Anual", 
         "Datosmacro", 
         "https://datosmacro.expansion.com/impuestos/iva/espana",
         "Negativo",
         "Aumento de la cantidad a pagar por este impuesto.",
         "Positivo",
         "Disminución la cantidad a pagar por este impuesto."),

        (104, "IVA superreducido", 
         "Impuesto sobre el Valor Añadido - Superreducido", 
         "Político", 
         "Porcentaje aplicado sobre el precio de un producto y que aumenta su precio este mismo porcentaje. Se aplica a productos básicos esenciales, como alimentos básicos o medicamentos", 
         "Porcentaje", 
         "%", 
         "Anual", 
         "Datosmacro", 
         "https://datosmacro.expansion.com/impuestos/iva/espana",
         "Negativo",
         "Aumento de la cantidad a pagar por este impuesto.",
         "Positivo",
         "Disminución la cantidad a pagar por este impuesto."),

        (105, "IRPF Medio", 
         "(Impuesto) sobre la Renta de las Personas Físicas – Tipo medio", 
         "Político", 
         "Porcentaje que grava los ingresos/rentas en función de su nivel de ingresos. Este indicador representa el tipo medio", 
         "Porcentaje", 
         "%", 
         "Anual", 
         "Datosmacro", 
         "https://datosmacro.expansion.com/impuestos/impuesto-renta-trabajadores/espana",
         "Negativo",
         "Aumento de la cantidad a pagar por este impuesto.",
         "Positivo",
         "Disminución la cantidad a pagar por este impuesto."),

         (106, "Ingresos fiscales", 
         "Ingresos fiscales", 
         "Político", 
         "Cantidad que se recauda a través de impuestos y retribuciones fiscales", 
         "Millones de euros", 
         "Mill.€", 
         "Anual", 
         "Datosmacro", 
         "https://datosmacro.expansion.com/impuestos/presion-fiscal/espana",
         "Negativo",
         "Aumento de la cantidad recaudada a través de impuestos, es decir, aumentan los pagos de impuestos.",
         "Positivo",
         "Disminución de la cantidad recaudada a través de impuestos, es decir, disminuyen los pagos de impuestos."),

        (107, "Presión fiscal (% PIB)", 
         "Porcentaje del PIB equivalente a la presión fiscal", 
         "Político", 
         "Proporción del PIB que se recauda a través de impuestos y retribuciones fiscales", 
         "Porcentaje", 
         "%", 
         "Anual", 
         "Datosmacro", 
         "https://datosmacro.expansion.com/impuestos/presion-fiscal/espana",
         "Negativo",
         "Aumento de la proporción de la producción (PIB) destinada a pagar impuestos.",
         "Positivo",
         "Disminución de la proporción de la producción (PIB) destinada a pagar impuestos."),

        (108, "Confianza en el Gobierno", 
         "Población que confía en el gobierno", 
         "Político", 
         "Porcentaje de la población que confía en el gobierno", 
         "Porcentaje", 
         "%", 
         "Anual", 
         "OECD", 
         "https://sdmx.oecd.org/public/rest/data/OECD.WISE.WDP,DSD_HSL@DF_HSL_FWB,/ESP.14_3.._T._T._T.?startPeriod=2004&endPeriod=2024&dimensionAtObservation=AllDimensions&format=csvfilewithlabels",
         "Positivo",
         "Aumento de la proporción de la población  que confía en el gobierno.",
         "Negativo",
         "Disminución de la proporción de la población  que confía en el gobierno."),

        (109, "Gasto en defensa", 
         "Gasto público en defensa", 
         "Político", 
         "Cifra del gasto público que está destinada a la defensa del país", 
         "Millones de euros", 
         "Mill.€", 
         "Anual", 
         "Datosmacro", 
         "https://datosmacro.expansion.com/estado/gasto/defensa/espana",
         "Positivo",
         "Aumento del gasto público destinado a defensa.",
         "Negativo",
         "Disminución del gasto público destinado a defensa."),

        (110, "Gasto en defensa (% PIB)", 
         "Porcentaje del PIB destinado a defensa", 
         "Político", 
         "Cifra del gasto público, medida como porcentaje del PIB, destinado a defensa", 
         "Porcentaje", 
         "%", 
         "Anual", 
         "Datosmacro", 
         "https://datosmacro.expansion.com/estado/gasto/defensa/espana",
         "Positivo",
         "Aumento del gasto público destinado a defensa.",
         "Negativo",
         "Disminución del gasto público destinado a defensa."),

        (111, "Personal de defensa", 
         "Personal de defensa militar (cualquier cuerpo)", 
         "Político",
         "Cifra total de militares alistados en cualquier cuerpo del ejército", 
         "Personas", 
         "Pers", 
         "Anual", 
         "Datosmacro", 
         "https://datosmacro.expansion.com/estado/defensa-ejercitos/espana",
         "Negativo",
         "Aumento de la cifra de militares alistados, aumentando el gasto público destinado a defensa.",
         "Positivo",
         "Disminución de la cifra de militares alistados, disminuyendo el gasto público destinado a defensa."),

        (200, "Negocios del sector comercio",
        "Cifra de negocios. Comercio al por mayor y al por menor; reparación de vehículos de motor y motocicletas",
        "Economía",
        "Valor de los negocios del sector de comercio, al por mayor, al por menor y la reparación de vehículos de motor y motocicletas",
        "Miles de euros",
        "K€",
        "Anual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=EEEC23934",
        "Positivo",
        "Aumento de la cifra de negocios del sector comercio.",
        "Negativo",
        "Disminución de la cifra de negocios del sector comercio."),

        (201, "Negocios del sector industrial",
        "Cifra de negocios. Industria",
        "Economía",
        "Valor de los negocios del sector industrial",
        "Miles de euros",
        "K€",
        "Anual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=EEEI97092",
         "Positivo",
        "Aumento de la cifra de negocios del sector industrial.",
        "Negativo",
        "Disminución de la cifra de negocios del sector industrial."),

        (202, "Negocios del sector servicios",
        "Cifra de negocios. Servicios",
        "Economía",
        "Valor de los negocios del sector servicios",
        "Miles de euros",
        "K€",
        "Anual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=EEES84918",
         "Positivo",
        "Aumento de la cifra de negocios del sector servicios.",
        "Negativo",
        "Disminución de la cifra de negocios del sector servicios."),

        (203, "Deudores concursados",
        "Deudores concursados. Total CNAE",
        "Economía",
        "Número de personas del CNAE que son deudores concursados (en procedimiento tras no poder cumplir sus obligaciones de pago)",
        "Personas",
        "Pers",
        "Trimestral",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=EPC4079",
         "Negativo",
         "Aumento del número de deudores concursados (en procedimiento tras no poder cumplir sus obligaciones de pago).",
         "Positivo",
         "Disminución del número de deudores concursados (en procedimiento tras no poder cumplir sus obligaciones de pago)."),

        (204, "Empresas concursadas",
        "Empresas concursadas. Total CNAE",
        "Economía",
        "Número de empresas del CNAE que son deudoras concursadas (en procedimiento tras no poder cumplir sus obligaciones de pago)",
        "Empresas",
        "Emps",
        "Trimestral",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=EPC6536",
         "Negativo",
         "Aumento del número de empresas concursadas (en procedimiento tras no poder cumplir sus obligaciones de pago).",
         "Positivo",
         "Disminución del número de empresas concursadas (en procedimiento tras no poder cumplir sus obligaciones de pago)."),

        (205, "Exportaciones de servicios",
        "Exportaciones. Total servicios",
        "Economía",
        "Valor de la exportación de negocios del sector servicios",
        "Millones de euros",
        "Mill.€",
        "Trimestral",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=ICES232",
         "Positivo",
         "Aumento de las exportaciones de servicios.",
         "Negativo",
         "Disminución de las exportaciones de servicios."),

        (206, "Viajes (españoles)",
        "Viajes que hace un español",
        "Economía",
        "Cantidad total de viajes realizados por españoles",
        "Viajes",
        "Vjs",
        "Trimestral",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=ETR220",
         "Positivo",
         "Aumento de la cifra de viajes realizados por españoles.",
         "Negativo",
         "Disminución de la cifra de viajes realizados por españoles."),

        (207, "Gasto / Turista",
        "Gasto medio por persona. Turista",
        "Economía",
        "Gasto medio que tiene un turista internacional en España",
        "Euros",
        "€",
        "Mensual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=FREG374",
         "Positivo",
         "Aumento del gasto medio de los turistas internacionales en España.",
         "Negativo",
         "Disminución del gasto medio de los turistas internacionales en España."),

        (208, "ICNE",
        "Índice de Cifra de Negocios Empresarial",
        "Economía",
        "Variación mensual de los ingresos generados por las empresas, positivo y negativo",
        "Porcentaje",
        "%",
        "Mensual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=ICNE195",
         "Positivo",
         "Aumento de los ingresos generados por las empresas.",
         "Negativo",
         "Disminución de los ingresos generados por las empresas."),

        (209, "Importaciones de servicios",
        "Importaciones. Total servicios",
        "Economía",
        "Valor de la importación de negocios del sector servicios",
        "Millones de euros",
        "Mill.€",
        "Trimestral",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=ICES217",
         "Positivo",
         "Aumento de las importaciones de servicios.",
         "Negativo",
         "Disminución de las importaciones de servicios."),

        (210, "Importe hipotecas",
        "Importe medio de hipotecas",
        "Economía",
        "Importe medio de las hipotecas concedidas",
        "Euros",
        "€",
        "Mensual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=HPT64397",
         "Negativo",
         "Aumento del importe medio de las hipotecas.",
         "Positivo",
         "Disminución del importe medio de las hipotecas."),

        (211, "Índice de negocios del sector servicios",
        "Cifra de negocio a precios corrientes. Total servicios",
        "Economía",
        "Variación mensual de la cifra de negocios del sector servicios",
        "Porcentaje",
        "%",
        "Mensual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=IAS4004",
         "Positivo",
         "Aumento de la cifra de negocios del sector servicios.",
         "Negativo",
         "Disminución de la cifra de negocios del sector servicios."),

        (212, "Índice de precios de vivienda",
        "Índice de precios de vivienda",
        "Economía",
        "Variación trimestral de los precios de vivienda",
        "Porcentaje",
        "%",
        "Trimestral",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=IPV948",
         "Negativo",
         "Aumento de los precios de las viviendas.",
         "Positivo",
         "Disminución de los precios de las viviendas."),

        (213, "Índice de precios del sector industrial",
        "Índice de precios. Mercado interior. Total industria",
        "Economía",
        "Variación mensual de los precios dentro del sector industrial, en el mercado interior",
        "Porcentaje",
        "%",
        "Mensual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=IPR34953",
         "Negativo",
         "Aumento de los precios dentro del sector industrial.",
         "Positivo",
         "Disminución de los precios dentro del sector industrial."),

        (214, "Índice de producción del sector servicios",
        "Índice de la cifra de negocio a precios corrientes. Total servicios",
        "Economía",
        "Variación mensual de la producción del sector servicios",
        "Porcentaje",
        "%",
        "Mensual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=IPSS194",
         "Positivo",
         "Aumento de la producción del sector servicios.",
         "Negativo",
         "Disminución de la producción del sector servicios."),

        (215, "Índice de producción del sector industrial",
        "Índice de la cifra de negocio a precios corrientes. Total industria",
        "Economía",
        "Variación mensual de la producción del sector industrial",
        "Porcentaje",
        "%",
        "Mensual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=IPI15374",
         "Positivo",
         "Aumento de la producción del sector industrial.",
         "Negativo",
         "Disminución de la producción del sector industrial."),

        (216, "Índice de existencias de mercaderías en comercio",
        "Índice del nivel de existencias de mercaderías en el comercio",
        "Economía",
        "Variación trimestral del nivel de las existencias de mercaderías en el comercio",
        "Porcentaje",
        "%",
        "Trimestral",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=ECSE102",
         "Positivo",
         "Aumento del nivel de las existencias de mercaderías en el comercio.",
         "Negativo",
         "Disminución del nivel de las existencias de mercaderías en el comercio."),

        (217, "Índice de existencias de mercaderías en comercio al por mayor",
        "Índice del nivel de existencias de mercaderías en el comercio al por mayor, excepto de vehículos de motor y motocicletas",
        "Economía",
        "Variación trimestral del nivel de las existencias de mercaderías en el comercio al por mayor",
        "Porcentaje",
        "%",
        "Trimestral",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=ECSE99",
         "Positivo",
         "Aumento del nivel de las existencias de mercaderías en el comercio al por mayor.",
         "Negativo",
         "Disminución del nivel de las existencias de mercaderías en el comercio al por mayor."),

        (218, "Índice de existencias de mercaderías en comercio al por menor",
        "Índice del nivel de existencias de mercaderías en el comercio al por menor, excepto de vehículos de motor y motocicletas",
        "Economía",
        "Variación trimestral del nivel de las existencias de mercaderías en el comercio al por menor",
        "Porcentaje",
        "%",
        "Trimestral",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=ECSE93",
         "Positivo",
         "Aumento del nivel de las existencias de mercaderías en el comercio al por menor.",
         "Negativo",
         "Disminución del nivel de las existencias de mercaderías en el comercio al por menor."),

        (219, "Índice general del comercio minorista",
        "Índice general. Cifra de negocio a precios constantes. Comercio al por menor, excepto de vehículos de motor y motocicletas",
        "Economía",
        "Variación mensual de las cifras, a precios constantes, de negocios minoristas",
        "Porcentaje",
        "%",
        "Mensual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=ICM4131",
         "Positivo",
         "Aumento de la cifra de negocios minoristas.",
         "Negativo",
         "Disminución de la cifra de negocios minoristas."),

        (220, "IPC",
        "Índice de Precios de Consumo",
        "Economía",
        "Variación mensual del precio de un consumo estándar, para medir la inflación",
        "Porcentaje",
        "%",
        "Mensual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=IPC251856",
         "Negativo",
         "Aumento del precio del consumo estándar, es decir, aumenta la inflación.",
         "Positivo",
         "Disminución del precio del consumo estándar, es decir, disminuye la inflación."),

        (221, "Cifra de turistas internacionales",
        "Cifra de turistas internacionales",
        "Economía",
        "Cifra de turistas internacionales que han llegado a España",
        "Personas",
        "Pers",
        "Mensual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=FREG297",
         "Positivo",
         "Aumento de la cifra de turistas internacionales que han llegado a España.",
         "Negativo",
         "Disminución de la cifra de turistas internacionales que han llegado a España."),

        (222, "PIB (precio de mercado)",
        "Producto Interior Bruto a precios de mercado",
        "Economía",
        "Valor de producción del país cada año, a precio de mercado (al que pagan los consumidores)",
        "Millones de euros",
        "Mill.€",
        "Anual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=CNE16231",
         "Positivo",
         "Aumento de la producción del país.",
         "Negativo",
         "Disminción de la producción del país."),

        (223, "Porcentaje de empresas (+10 empleados) con Internet",
        "Porcentaje de empresas (+10 empleados) con conexión a Internet",
        "Economía",
        "Porcentaje de empresas con más de 10 empleados que tienen conexión a Internet",
        "Porcentaje",
        "%",
        "Anual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=DCC363",
         "Positivo",
         "Aumento del porcentaje de empresas con más de 10 empleados que tienen Internet.",
         "Negativo",
         "Disminución del porcentaje de empresas con más de 10 empleados que tienen Internet."),

        (224, "Porcentaje de empresas (-10 empleados) con Internet",
        "Porcentaje de empresas (-10 empleados) con conexión a Internet",
        "Economía",
        "Porcentaje de empresas con menos de 10 empleados que tienen conexión a Internet",
        "Porcentaje",
        "%",
        "Anual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=DCC364",
         "Positivo",
         "Aumento del porcentaje de empresas con menos de 10 empleados que tienen Internet.",
         "Negativo",
         "Disminución del porcentaje de empresas con menos de 10 empleados que tienen Internet."),

        (225, "Porcentaje de empresas (+10 empleados) con Internet y página web",
        "Porcentaje de empresas (+10 empleados) con conexión a Internet y página web",
        "Economía",
        "Porcentaje de empresas con más de 10 empleados que tienen conexión a Internet y página web",
        "Porcentaje",
        "%",
        "Anual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=DCC361",
         "Positivo",
         "Aumento del porcentaje de empresas con más de 10 empleados que tienen Internet y página web.",
         "Negativo",
         "Disminución del porcentaje de empresas con más de 10 empleados que tienen Internet y página web."),

        (226, "Porcentaje de empresas (-10 empleados) con Internet y página web",
        "Porcentaje de empresas (-10 empleados) con conexión a Internet y página web",
        "Economía",
        "Porcentaje de empresas con menos de 10 empleados que tienen conexión a Internet y página web",
        "Porcentaje",
        "%",
        "Anual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=DCC362",
         "Positivo",
         "Aumento del porcentaje de empresas con menos de 10 empleados que tienen Internet y página web.",
         "Negativo",
         "Disminución del porcentaje de empresas con menos de 10 empleados que tienen Internet y página web."),

        (227, "Porcentaje de empresas (+10 empleados) con ordenadores",
        "Porcentaje de empresas (+10 empleados) que disponen de ordenadores",
        "Economía",
        "Porcentaje de empresas con más de 10 empleados que disponen de ordenadores",
        "Porcentaje",
        "%",
        "Anual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=DCC365",
         "Positivo",
         "Aumento del porcentaje de empresas con más de 10 empleados que tienen ordenadores.",
         "Negativo",
         "Disminución del porcentaje de empresas con más de 10 empleados que tienen ordenadores."),

        (228, "Porcentaje de empresas (-10 empleados) con ordenadores",
        "Porcentaje de empresas (-10 empleados) que disponen de ordenadores",
        "Economía",
        "Porcentaje de empresas con menos de 10 empleados que disponen de ordenadores",
        "Porcentaje",
        "%",
        "Anual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=DCC366",
         "Positivo",
         "Aumento del porcentaje de empresas con menos de 10 empleados que tienen ordenadores.",
         "Negativo",
         "Disminución del porcentaje de empresas con menos de 10 empleados que tienen ordenadores."),

        (229, "Porcentaje de empresas (+10 empleados) que compran online",
        "Porcentaje de empresas (+10 empleados) que realizan compras por comercio electrónico",
        "Economía",
        "Porcentaje de empresas con más de 10 empleados que realizan compras por comercio electrónico",
        "Porcentaje",
        "%",
        "Anual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=DCC355",
         "Positivo",
         "Aumento del porcentaje de empresas con más de 10 empleados que compran online.",
         "Negativo",
         "Disminución del porcentaje de empresas con más de 10 empleados que compran online."),

        (230, "Porcentaje de empresas (-10 empleados) que compran online",
        "Porcentaje de empresas (-10 empleados) que realizan compras por comercio electrónico",
        "Economía",
        "Porcentaje de empresas con menos de 10 empleados que realizan compras por comercio electrónico",
        "Porcentaje",
        "%",
        "Anual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=DCC356",
         "Positivo",
         "Aumento del porcentaje de empresas con menos de 10 empleados que compran online.",
         "Negativo",
         "Disminución del porcentaje de empresas con menos de 10 empleados que compran online."),

        (231, "Porcentaje de empresas (+10 empleados) que venden online",
        "Porcentaje de empresas (+10 empleados) que realizan ventas por comercio electrónico",
        "Economía",
        "Porcentaje de empresas con más de 10 empleados que realizan ventas por comercio electrónico",
        "Porcentaje",
        "%",
        "Anual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=DCC357",
         "Positivo",
         "Aumento del porcentaje de empresas con más de 10 empleados que venden online.",
         "Negativo",
         "Disminución del porcentaje de empresas con más de 10 empleados que venden online."),

        (232, "Porcentaje de empresas (-10 empleados) que venden online",
        "Porcentaje de empresas (-10 empleados) que realizan ventas por comercio electrónico",
        "Economía",
        "Porcentaje de empresas con menos de 10 empleados que realizan ventas por comercio electrónico",
        "Porcentaje",
        "%",
        "Anual",
        "ine",
         ""
        "https://www.ine.es/consul/serie.do?d=true&s=DCC358",
         "Positivo",
         "Aumento del porcentaje de empresas con menos de 10 empleados que venden online.",
         "Negativo",
         "Disminución del porcentaje de empresas con menos de 10 empleados que venden online."),

        (233, "Renta / Hogar",
        "Renta neta media por hogar",
        "Economía",
        "Cifra de la renta media anual de los españoles por cada hogar",
        "Euros",
        "€",
        "Anual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=ECV3959",
         "Positivo",
         "Aumento de la renta media por cada hogar.",
         "Negativo",
         "Disminución de la renta media por cada hogar."),

        (234, "Renta nacional bruta",
        "Renta nacional bruta",
        "Economía",
        "Cifra total de los ingresos generados por los residentes de España cada año",
        "Millones de euros",
        "Mill.€",
        "Anual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=CNE16233",
         "Positivo",
         "Aumento de los ingresos generados por los residentes de España.",
         "Negativo",
         "Disminución de los ingresos generados por los residentes de España."),

        (235, "Renta nacional bruta disponible",
        "Renta nacional bruta disponible",
        "Economía",
        "Cifra total de los ingresos disponibles para los residentes de España, teniendo en cuenta los generados y las transferencias internacionales recibidas",
        "Millones de euros",
        "Mill.€",
        "Anual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=CNE16234",
         "Positivo",
         "Aumento de los ingresos disponibles para los residentes de España.",
         "Negativo",
         "Disminución de los ingresos disponibles para los residentes de España."),

        (236, "Sociedades mercantiles creadas",
        "Sociedades mercantiles creadas",
        "Economía",
        "Cifra de sociedades mercantiles creadas cada mes en España",
        "Empresas",
        "Emps",
        "Mensual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=SM21483",
         "Positivo",
         "Aumento de la cifra de sociedades mercantiles creadas.",
         "Negativo",
         "Disminución de la cifra de sociedades mercantiles creadas."),

        (237, "Sociedades mercantiles disueltas",
        "Sociedades mercantiles disueltas",
        "Economía",
        "Cifra de sociedades mercantiles disueltas cada mes en España",
        "Empresas",
        "Emps",
        "Mensual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=SM21486",
         "Negativo",
         "Aumento de la cifra de sociedades mercantiles disueltas.",
         "Positivo",
         "Disminución de la cifra de sociedades mercantiles disueltas."),

        (238, "Ahorro total de hogares",
        "Ahorro total de hogares",
        "Economía",
        "Cifra de ahorro del total de hogares españoles cada año",
        "Millones de euros",
        "Mill.€",
        "Anual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=DCE78",
         "Negativo",
         "Aumento de la cifra de ahorro del total de hogares.",
         "Positivo",
         "Disminución de la cifra de ahorro del total de hogares."),

        (239, "Tasa de muertes de empresas",
        "Tasa de muertes de empresas (total sectores)",
        "Economía",
        "Porcentaje de empresas disueltas cada año en España, teniendo en cuenta todos los sectores",
        "Porcentaje",
        "%",
        "Anual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=DCE19",
         "Negativo",
         "Aumento del porcentaje de empresas disueltas.",
         "Positivo",
         "Disminución del porcentaje de empresas disueltas."),

        (240, "Tasa de nacimientos de empresas",
        "Tasa de nacimientos de empresas (total sectores)",
        "Economía",
        "Porcentaje de empresas creadas cada año en España, teniendo en cuenta todos los sectores",
        "Porcentaje",
        "%",
        "Anual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=DCE14",
         "Positivo",
         "Aumento del porcentaje de empresas creadas.",
         "Negativo",
         "Disminución del porcentaje de empresas creadas."),

        (241, "Tipo de interés medio de hipotecas",
        "Tipo de interés medio de hipotecas para viviendas",
        "Economía",
        "Valor del tipo de interés medio que tienen las hipotecas para las viviendas cada mes",
        "Porcentaje",
        "%",
        "Mensual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=HPT64408",
         "Negativo",
         "Aumento del tipo de interés medio que tienen las hipotecas para las viviendas.",
         "Positivo",
         "Disminución del tipo de interés medio que tienen las hipotecas para las viviendas."),

        (242, "Compras al sector comercial",
        "Total de compras de bienes y servicios. Comercio al por mayor y al por menor; reparación de vehículos de motor y motocicletas",
        "Economía",
        "Valor del total de las compras de bienes y servicios realizadas al sector comercial cada año",
        "Miles de euros",
        "K€",
        "Anual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=EEEC23470",
         "Positivo",
         "Aumento del valor total de las compras de bienes y servicios realizadas al sector comercial.",
         "Negativo",
         "Disminución del valor total de las compras de bienes y servicios realizadas al sector comercial."),

        (243, "Compras al sector servicios",
        "Total de compras de bienes y servicios. Sector servicios",
        "Economía",
        "Valor del total de las compras de bienes y servicios realizadas al sector servicios cada año",
        "Miles de euros",
        "K€",
        "Anual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=EEES83854",
         "Positivo",
         "Aumento del valor total de las compras de bienes y servicios realizadas al sector servicios.",
         "Negativo",
         "Disminución del valor total de las compras de bienes y servicios realizadas al sector servicios."),

        (244, "Compras al sector industrial",
        "Total de compras de bienes y servicios. Sector industrial",
        "Economía",
        "Valor del total de las compras de bienes y servicios realizadas al sector industrial cada año",
        "Miles de euros",
        "K€",
        "Anual",
        "ine",
        "https://www.ine.es/consul/serie.do?d=true&s=EEEI99624",
         "Positivo",
         "Aumento del valor total de las compras de bienes y servicios realizadas al sector industrial.",
         "Negativo",
         "Disminución del valor total de las compras de bienes y servicios realizadas al sector industrial."),

        (245, "Deuda pública", 
        "Deuda pública", 
        "Economía", 
        "Valor de la deuda contraída por el gobierno para financiar los gastos cuando los ingresos no son suficientes", 
        "Millones de euros", 
        "Mill.€", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/deuda/espana",
         "Negativo",
         "Aumento de la deuda contraída por el gobierno para financiar gastos.",
         "Positivo",
         "Aumento de la deuda contraída por el gobierno para financiar gastos."),

        (246, "Gasto público", 
        "Gasto público", 
        "Economía", 
        "Cantidad destinada por el gobierno para satisfacer las necesidades de la sociedad", 
        "Millones de euros", 
        "Mill.€", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/estado/gasto/espana",
         "Positivo",
         "Aumento del gasto destinado a satisfacer las necesidades de la sociedad.",
         "Negativo",
         "Disminución del gasto destinado a satisfacer las necesidades de la sociedad."),

        (247, "Gasto público (% PIB)", 
        "Porcentaje del PIB destinado al gasto público", 
        "Economía", 
        "Porcentaje del Producto Interior Bruto que el gobierno destina al gasto público", 
        "Millones de euros", 
        "Mill.€", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/estado/gasto/espana",
         "Positivo",
         "Aumento del gasto destinado a satisfacer las necesidades de la sociedad.",
         "Negativo",
         "Disminución del gasto destinado a satisfacer las necesidades de la sociedad."),

        (248, "Índice de competitividad", 
        "Índice de competitividad global", 
        "Economía", 
        "Mide la capacidad de un país para ofrecer un entorno favorable para negocios y desarrollo económico, evaluado del 0 (baja competitividad) al 100 (alta competitividad)", 
        "Escala de 0 (nivel bajo) a 100 (nivel alto)", 
        "0(-) / 100(+)", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/estado/indice-competitividad-global/espana",
         "Positivo",
         "Aumento de la capacidad del país para ofrecer un entorno favorable para negocios y desarrollo económico.",
         "Negativo",
         "Disminución de la capacidad del país para ofrecer un entorno favorable para negocios y desarrollo económico."),

        (249, "Índice de innovación", 
        "Índice de mundial de innovación", 
        "Economía", 
        "Mide la capacidad de un país para desarrollar y aplicar ideas innovadoras, evaluado del 0 (baja competitividad) al 100 (alta competitividad)", 
        "Escala de 0 (nivel bajo) a 100 (nivel alto)", 
        "0(-) / 100(+)", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/estado/indice-mundial-innovacion/espana",
         "Positivo",
         "Aumento de la capacidad del país para desarrollar y aplicar ideas innovadoras.",
         "Negativo",
         "Disminución de la capacidad del país para desarrollar y aplicar ideas innovadoras."),

        (250, "Exportaciones", 
        "Exportaciones de mercancías", 
        "Economía", 
        "Valor de los bienes y servicios producidos en España y vendidos a otro país", 
        "Millones de euros", 
        "Mill.€", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/comercio/exportaciones/espana",
         "Positivo",
         "Aumento del valor de los bienes y servicios exportados.",
         "Negativo",
         "Disminución del valor de los bienes y servicios exportados."),

        (251, "Exportaciones (% PIB)", 
        "Porcentaje del PIB referente a exportaciones de mercancías", 
        "Economía", 
        "Porcentaje del PIB referente a los bienes y servicios producidos en España y vendidos a otro país", 
        "Porcentaje", 
        "%", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/comercio/exportaciones/espana",
         "Positivo",
         "Aumento del porcentaje del PIB referente a las exportaciones.",
         "Negativo",
         "Disminución del porcentaje del PIB referente a las exportaciones."),

        (252, "Importaciones", 
        "Importaciones de mercancías", 
        "Economía", 
        "Valor de los bienes y servicios producidos en otro país y comprados por España", 
        "Millones de euros", 
        "Mill.€", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/comercio/importaciones/espana",
         "Positivo",
         "Aumento del valor de los bienes y servicios importados.",
         "Negativo",
         "Disminución del valor de los bienes y servicios importados."),

        (253, "Importaciones (% PIB)", 
        "Porcentaje del PIB referente a importaciones de mercancías", 
        "Economía", 
        "Porcentaje del PIB referente a los bienes y servicios producidos en otro país y comprados por España", 
        "Porcentaje", 
        "%", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/comercio/importaciones/espana",
         "Positivo",
         "Aumento del porcentaje del PIB referente a las importaciones.",
         "Negativo",
         "Disminución del porcentaje del PIB referente a las importaciones."),

        (254, "Renta media anual", 
        "Renta media anual", 
        "Economía", 
        "Valor medio de la renta recibida, al año, por los trabajadores", 
        "Euros", 
        "€", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/mercado-laboral/salario-medio/espana",
         "Positivo",
         "Aumento de la renta media anual recibida por los trabajadores.",
         "Negativo",
         "Disminución de la renta media anual recibida por los trabajadores."),

        (255, "Renta mínima anual", 
        "Renta mínima anual", 
        "Economía", 
        "Valor mínimo establecido de la renta recibida, al año, por los trabajadores", 
        "Euros", 
        "€", 
        "Semestral", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/smi/espana",
         "Positivo",
         "Aumento del valor mínimo establecido para la renta anual de los trabajadores.",
         "Negativo",
         "Disminución del valor mínimo establecido para la renta anual de los trabajadores."),

        (256, "PPA", 
        "Paridades de poder adquisitivo", 
        "Economía", 
        "Poder adquisitivo de los residentes del país. Un aumento del PPA implica una mayor capacidad adquisitiva.", 
        "Euros", 
        "€", 
        "Anual", 
        "Eurostat", 
        "https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/data/prc_ppp_ind/A.EXP_PPS_EU27_2020.A01.ES?format=SDMX-CSV&lang=en&label=label_only&startPeriod=2014&endPeriod=2023",
         "Positivo",
         "Aumento del poder adquisitivo de los residentes del país.",
         "Negativo",
         "Disminución del poder adquisitivo de los residentes del país."),

        (257, "Tipo de cambio - USD", 
        "Tipo de cambio entre el dólar y el euro", 
        "Economía", 
        "Evolución del valor del dólar equivalente a un euro", 
        "Dólar por cada euro", 
        "USD/€", 
        "Anual", 
        "Eurostat", 
        "https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/data/ert_bil_eur_a/A.AVG.NAC.USD?format=SDMX-CSV&lang=en&label=label_only&startPeriod=2015&endPeriod=2024",
         "Negativo",
         "Aumento del valor del dólar equivalente a un euro.",
         "Positivo",
         "Disminución del valor del dólar equivalente a un euro."),

        (258, "Tipo de cambio – GBP", 
        "Tipo de cambio entre la libra esterlina y el euro", 
        "Economía", 
        "Evolución del valor de la libra esterlina equivalente a un euro", 
        "Libra por cada euro", 
        "GBP/€", 
        "Anual", 
        "Eurostat", 
        "https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/data/ert_bil_eur_a/A.AVG.NAC.GBP?format=SDMX-CSV&lang=en&label=label_only&startPeriod=2015&endPeriod=2024",
         "Negativo",
         "Aumento del valor de la libra esterlina equivalente a un euro.",
         "Positivo",
         "Disminución del valor de la libra esterlina equivalente a un euro."),

        (259, "Tipo de cambio – JPY", 
        "Tipo de cambio entre el yen japonés y el euro", 
        "Economía", 
        "Evolución del valor del yen japonés equivalente a un euro", 
        "Yen por cada euro", 
        "JPY/€", 
        "Anual", 
        "Eurostat", 
        "https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/data/ert_bil_eur_a/A.AVG.NAC.JPY?format=SDMX-CSV&lang=en&label=label_only&startPeriod=2015&endPeriod=2024",
         "Negativo",
         "Aumento del valor del yen japonés equivalente a un euro.",
         "Positivo",
         "Disminución del valor del yen japonés equivalente a un euro."),

        (260, "Tipo de cambio – CNY", 
        "Tipo de cambio entre el yuan chino y el euro", 
        "Economía", 
        "Evolución del valor del yuan chino equivalente a un euro", 
        "Yuan por cada euro", 
        "CNY/€", 
        "Anual", 
        "Eurostat", 
        "https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/data/ert_bil_eur_a/A.AVG.NAC.CNY?format=SDMX-CSV&lang=en&label=label_only&startPeriod=2015&endPeriod=2024",
         "Negativo",
         "Aumento del valor del yuan chino equivalente a un euro.",
         "Positivo",
         "Disminución del valor del yuan chino equivalente a un euro."),

        (261, "Tipo de cambio – CHF", 
        "Tipo de cambio entre el franco suizo y el euro", 
        "Economía", 
        "Evolución del valor del franco suizo equivalente a un euro", 
        "Franco por cada euro", 
        "CHF/€", 
        "Anual", 
        "Eurostat", 
        "https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/data/ert_bil_eur_a/A.AVG.NAC.CHF?format=SDMX-CSV&lang=en&label=label_only&startPeriod=2015&endPeriod=2024",
         "Negativo",
         "Aumento del valor del franco suizo equivalente a un euro.",
         "Positivo",
         "Disminución del valor del franco suizo equivalente a un euro."),

        (262, "Tipo de cambio – AUD", 
        "Tipo de cambio entre el dólar australiano y el euro", 
        "Economía", 
        "Evolución del valor del dólar australiano equivalente a un euro", 
        "Franco por cada euro", 
        "AUD/€", 
        "Anual", 
        "Eurostat", 
        "https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/data/ert_bil_eur_a/A.AVG.NAC.AUD?format=SDMX-CSV&lang=en&label=label_only&startPeriod=2015&endPeriod=2024",
         "Negativo",
         "Aumento del valor del dólar australiano equivalente a un euro.",
         "Positivo",
         "Disminución del valor del dólar australiano equivalente a un euro."),

        (263, "Tipo de interés BCE", 
        "Tipo de interés del Banco Central Europeo", 
        "Economía", 
        "Interés por el que el BCE presta dinero", 
        "Porcentaje", 
        "%", 
        "Mensual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/tipo-interes/zona-euro",
         "Negativo",
         "Aumento del tipo de interés del BCE.",
         "Positivo",
         "Disminución del tipo de interés del BCE."),

        (264, "ICH", 
        "Índice de Capital Humano", 
        "Economía", 
        "Mide el nivel de desarrollo de capital humano, teniendo en cuenta el nivel educativo, habilidades, aptitudes y calificación. Determina en gran parte su éxito económico a largo plazo, viendo si el país aprovecha su potencial humano", 
        "Escala de 0 (nivel bajo) a 1 (nivel alto)", 
        "0(-) / 1(+)", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/mercado-laboral/capital-humano/espana",
         "Positivo",
         "Aumento del nivel de desarrollo de capital humano (mayor nivel educativo, habilidades, aptitudes...).",
         "Negativo",
         "Disminución del nivel de desarrollo de capital humano (menor nivel educativo, habilidades, aptitudes...)."),

        (265, "Índice Doing Business", 
        "Índice Doing Business", 
        "Economía", 
        "Mide la facilidad para hacer negocios en el país, teniendo en cuenta las facilidades que ofrece el país para abrir un negocio y obtener créditos, la protección a los inversores, el manejo de permisos de construcción, etc.", 
        "Escala de 0 (nivel bajo) a 100 (nivel alto)", 
        "0(-) / 100(+)", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/negocios/doing-business/espana",
         "Positivo",
         "Mayor facilidad para hacer negocios en el país.",
         "Negativo",
         "Menor facilidad para hacer negocios en el país."),

        (300, "Coste laboral / Trabajador", 
        "Coste laboral neto por trabajador. Industria, construcción y servicios (excepto actividades de los hogares como empleadores y de organizaciones y organismos extraterritoriales)", 
        "Social", 
        "Coste total neto que cada trabajador cuesta a la empresa en un año", 
        "Euros", 
        "€", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=EACL188",
         "Negativo",
         "Aumento del coste laboral neto por trabajador.",
         "Positvo",
         "Disminución del coste laboral neto por trabajador."),

        (301, "Emigración", 
        "Flujo de emigraciones con destino el extranjero. Todas las edades", 
        "Social", 
        "Cifra de movimientos migratorios hacia el extranjero, teniendo en cuenta todas las edades", 
        "Movimientos migratorios", 
        "Mov.Mig", 
        "Semestral", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=EM74065",
         "Negativo",
         "Aumento del flujo de emigraciones (migraciones hacia el extranjero.)",
         "Positivo",
         "Disminución del flujo de emigraciones (migraciones hacia el extranjero.)"),

        (302, "Ganancia / Trabajador", 
        "Ganancia media anual por trabajador", 
        "Social", 
        "Valor medio de lo que gana cada trabajador en un año", 
        "Euros", 
        "€", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=EAES93560",
         "Positivo",
         "Aumento del valor medio de lo que gana cada trabajador.",
         "Negativo",
         "Disminución del valor medio de lo que gana cada trabajador."),

        (303, "Inmigración", 
        "Flujo de inmigraciones procedentes del extranjero. Todas las edades", 
        "Social", 
        "Cifra de movimientos migratorios con España como destino, teniendo en cuenta todas las edades", 
        "Movimientos migratorios", 
        "Mov.Mig", 
        "Semestral", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=EM74065",
         "Positivo",
         "Aumento del flujo de inmigraciones (migraciones hacia España.)",
         "Negativo",
         "Disminución del flujo de inmigraciones (migraciones hacia España.)"),

        (304, "IPT", 
        "Índices de Precios de Trabajo", 
        "Social", 
        "Evolución anual del coste de la mano de obra", 
        "Porcentaje", 
        "%", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=IPT287",
         "Negativo",
         "Aumento del coste de la mano de obra.",
         "Positivo",
         "Disminución del coste de la mano de obra."),

        (305, "Población femenina", 
        "Población femenina residente en España. Todas las edades", 
        "Social", 
        "Cifra total de mujeres que residen en España cada trimestre", 
        "Personas", 
        "Pers", 
        "Trimestral", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=ECP318",
         "Positivo",
         "Aumento de la población femenina residente en España.",
         "Negativo",
         "Disminución de la población femenina residente en España."),

        (306, "Población masculina", 
        "Población masculina residente en España. Todas las edades", 
        "Social", 
        "Cifra total de hombres que residen en España cada trimestre", 
        "Personas", 
        "Pers", 
        "Trimestral", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=ECP319",
         "Positivo",
         "Aumento de la población masculina residente en España.",
         "Negativo",
         "Disminución de la población masculina residente en España."),

        (307, "Población", 
        "Población residente en España. Todas las edades", 
        "Social", 
        "Cifra total de personas que residen en España cada trimestre", 
        "Personas", 
        "Pers", 
        "Trimestral", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=ECP320",
         "Positivo",
         "Aumento de la población residente en España.",
         "Negativo",
         "Disminución de la población residente en España."),

        (308, "Mortalidad", 
        "Tasa bruta de mortalidad", 
        "Social", 
        "Cifra total de defunciones cada 1.000 habitantes, representada con su respectivo porcentaje", 
        "Porcentaje", 
        "%", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=IDB47797",
         "Negativo",
         "Aumento de la cifra total de defunciones cada 1.000 habitantes.",
         "Positivo",
         "Disminución de la cifra total de defunciones cada 1.000 habitantes."),

        (309, "Tasa de actividad", 
        "Tasa de actividad. Ambos sexos. 16 y más años", 
        "Social", 
        "Porcentaje de personas activas (con trabajo o buscándolo) en el total de la población mayor de 16 años", 
        "Porcentaje", 
        "%", 
        "Trimestral", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=EPA388079",
         "Positivo",
         "Aumento del porcentaje de personas activas (con trabajo o buscándolo).",
         "Negativo",
         "Disminución del porcentaje de personas activas (con trabajo o buscándolo)."),

        (310, "Tasa de desempleo", 
        "Tasa de paro de la población. Ambos sexos. 16 y más años", 
        "Social", 
        "Porcentaje de personas desempleadas dentro del total de la población activa", 
        "Porcentaje", 
        "%", 
        "Trimestral", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=EPA423474",
         "Negativo",
         "Aumento del porcentaje de personas desempleadas dentro del total de la población activa.",
         "Positivo",
         "Disminución del porcentaje de personas desempleadas dentro del total de la población activa."),

        (311, "Esperanza de vida sana", 
        "Esperanza de vida sana", 
        "Social", 
        "Edad hasta la que se espera que una persona pueda vivir con buena salud", 
        "Años", 
        "Años", 
        "Anual", 
        "Eurostat", 
        "https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/data/hlth_hlye/A.YR.T.HLY_0.ES?format=SDMX-CSV&lang=en&label=label_only",
         "Positivo",
         "Aumento de la edad hasta la que se espera que una persona pueda vivir con buena salud.",
         "Negativo",
         "Disminución de la edad hasta la que se espera que una persona pueda vivir con buena salud."),

        (312, "Población -18 años", 
        "Población menor de 18 años", 
        "Social", 
        "Porcentaje de la población con menos de 18 años, menor de edad", 
        "Porcentaje", 
        "%", 
        "Anual", 
        "Eurostat", 
        "https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/data/ilc_lvps01/A.Y_LT18.T.PC.ES?format=SDMX-CSV&lang=en&label=label_only",
         "Positivo",
         "Aumento del porcentaje de la población con menos de 18 años.",
         "Negativo",
         "Disminución del porcentaje de la población con menos de 18 años."),

        (313, "Población 18 – 24 años", 
        "Población entre 18 y 24 años", 
        "Social", 
        "Porcentaje de la población que tiene entre 18 y 24 años", 
        "Porcentaje", 
        "%", 
        "Anual", 
        "Eurostat", 
        "https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/data/ilc_lvps01/A.Y18-24.T.PC.ES?format=SDMX-CSV&lang=en&label=label_only",
         "Positivo",
         "Aumento del porcentaje de la población que tiene entre 18 y 24 años.",
         "Negativo",
         "Disminución del porcentaje de la población que tiene entre 18 y 24 años."),

        (314, "Población 25 – 49 años", 
        "Población entre 25 y 49 años", 
        "Social", 
        "Porcentaje de la población que tiene entre 25 y 49 años", 
        "Porcentaje", 
        "%", 
        "Anual", 
        "Eurostat", 
        "https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/data/ilc_lvps01/A.Y25-49.T.PC.ES?format=SDMX-CSV&lang=en&label=label_only",
         "Positivo",
         "Aumento del porcentaje de la población que tiene entre 25 y 49 años.",
         "Negativo",
         "Disminución del porcentaje de la población que tiene entre 25 y 49 años."),

        (315, "Población 50 – 64 años", 
        "Población entre 50 y 64 años", 
        "Social", 
        "Porcentaje de la población que tiene entre 50 y 64 años", 
        "Porcentaje", 
        "%", 
        "Anual", 
        "Eurostat", 
        "https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/data/ilc_lvps01/A.Y50-64.T.PC.ES?format=SDMX-CSV&lang=en&label=label_only",
         "Positivo",
         "Aumento del porcentaje de la población que tiene entre 50 y 64 años.",
         "Negativo",
         "Disminución del porcentaje de la población que tiene entre 50 y 64 años."),

        (316, "Población +65 años", 
        "Población mayor de 65 años", 
        "Social", 
        "Porcentaje de la población con más de 65 años", 
        "Porcentaje", 
        "%", 
        "Anual", 
        "Eurostat", 
        "https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/data/ilc_lvps01/A.Y_GE65.T.PC.ES?format=SDMX-CSV&lang=en&label=label_only",
         "Positivo",
         "Aumento del porcentaje de la población con más de 65 años.",
         "Negativo",
         "Disminución del porcentaje de la población con más de 65 años."),

        (317, "Esperanza de vida", 
        "Esperanza de vida al nacer", 
        "Social", 
        "Edad, de media, hasta la que se espera que una persona viva", 
        "Años", 
        "Años", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/demografia/esperanza-vida/espana",
         "Positivo",
         "Aumento de la edad, de media, hasta la que se espera que una persona viva.",
         "Negativo",
         "Disminución de la edad, de media, hasta la que se espera que una persona viva."),

        (318, "Esperanza de vida (mujeres)", 
        "Esperanza de vida al nacer (mujeres)", 
        "Social", 
        "Edad, de media, hasta la que se espera que una mujer viva", 
        "Años", 
        "Años", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/demografia/esperanza-vida/espana",
         "Positivo",
         "Aumento de la edad, de media, hasta la que se espera que una mujer viva.",
         "Negativo",
         "Disminución de la edad, de media, hasta la que se espera que una mujer viva."),

        (319, "Esperanza de vida (hombres)", 
        "Esperanza de vida al nacer (hombres)", 
        "Social", 
        "Edad, de media, hasta la que se espera que un hombre viva", 
        "Años", 
        "Años", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/demografia/esperanza-vida/espana",
         "Positivo",
         "Aumento de la edad, de media, hasta la que se espera que un hombre viva.",
         "Negativo",
         "Disminución de la edad, de media, hasta la que se espera que un hombre viva."),

        (320, "Matrimonios", 
        "Total de matrimonios al año", 
        "Social", 
        "Cifra total de matrimonios contraídos cada año", 
        "Matrimonios", 
        "Matr", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/demografia/matrimonios/espana",
         "Positivo",
         "Aumento de la cifra total de matrimonios contraídos.",
         "Negativo",
         "Disminución de la cifra total de matrimonios contraídos."),

        (321, "Tasa nupcialidad", 
        "Tasa bruta de nupcialidad", 
        "Social", 
        "Cantidad de matrimonios contraídos por cada 1.000 habitantes", 
        "Porcentaje", 
        "%", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/demografia/matrimonios/espana",
         "Positivo",
         "Aumento de la cantidad de matrimonios contraídos por cada 1.000 habitantes.",
         "Negativo",
         "Disminución de la cantidad de matrimonios contraídos por cada 1.000 habitantes."),

        (322, "Divorcios", 
        "Total de divorcios al año", 
        "Social", 
        "Cifra total de divorcios realizados cada año", 
        "Divorcios", 
        "Div", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/demografia/divorcios/espana",
         "Negativo",
         "Aumento de la cifra total de divorcios.",
         "Positivo",
         "Disminución de la cifra total de divorcios."),

        (323, "Tasa divorcios", 
        "Tasa bruta de divorcios", 
        "Social", 
        "Cantidad de divorcios realizados por cada 1.000 habitantes", 
        "Porcentaje", 
        "%", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/demografia/divorcios/espana",
         "Negativo",
         "Aumento de la cantidad de divorcios realizados por cada 1.000 habitantes.",
         "Positivo",
         "Disminución de la cantidad de divorcios realizados por cada 1.000 habitantes."),

        (324, "Suicidios", 
        "Total de suicidios al año", 
        "Social", 
        "Cifra total de suicidios cada año", 
        "Suicidios", 
        "Suic", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/demografia/mortalidad/causas-muerte/suicidio/espana",
         "Negativo",
         "Aumento de la cifra total de suicidios.",
         "Positivo",
         "Disminución de la cifra total de suicidios."),

        (325, "Tasa suicidios", 
        "Tasa bruta de suicidios", 
        "Social", 
        "Cantidad de suicidios por cada 100.000 habitantes", 
        "Porcentaje", 
        "%", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/demografia/mortalidad/causas-muerte/suicidio/espana",
         "Negativo",
         "Aumento de la cantidad de suicidios por cada 100.000 habitantes.",
         "Positivo",
         "Disminución de la cantidad de suicidios por cada 100.000 habitantes." ),

        (326, "Suicidios (mujeres)", 
        "Total de suicidios al año (mujeres)", 
        "Social", 
        "Cifra total de suicidios de mujeres cada año", 
        "Suicidios", 
        "Suic", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/demografia/mortalidad/causas-muerte/suicidio/espana",
         "Negativo",
         "Aumento de la cifra total de suicidios de mujeres.",
         "Positivo",
         "Disminución de la cifra total de suicidios de mujeres."),

        (327, "Tasa suicidios (mujeres)", 
        "Tasa bruta de suicidios (mujeres)", 
        "Social", 
        "Cantidad de suicidios de mujeres por cada 100.000 mujeres", 
        "Porcentaje", 
        "%", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/demografia/mortalidad/causas-muerte/suicidio/espana",
         "Negativo",
         "Aumento de la cantidad de suicidios de mujeres por cada 100.000 mujeres.",
         "Positivo",
         "Disminución de la cantidad de suicidios de mujeres por cada 100.000 mujeres."),

        (328, "Suicidios (hombres)", 
        "Total de suicidios al año (hombres)", 
        "Social", 
        "Cifra total de suicidios de hombres cada año", 
        "Suicidios", 
        "Suic", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/demografia/mortalidad/causas-muerte/suicidio/espana",
         "Negativo",
         "Aumento de la cifra total de suicidios de hombres.",
         "Positivo",
         "Disminución de la cifra total de suicidios de hombres."),

        (329, "Tasa suicidios (hombres)", 
        "Tasa bruta de suicidios (hombres)", 
        "Social", 
        "Cantidad de suicidios de hombres por cada 100.000 hombres", 
        "Porcentaje", 
        "%", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/demografia/mortalidad/causas-muerte/suicidio/espana",
         "Negativo",
         "Aumento de la cantidad de suicidios de hombres por cada 100.000 hombres.",
         "Positivo",
         "Disminución de la cantidad de suicidios de hombres por cada 100.000 hombres."),

        (330, "Población atea", 
        "Porcentaje de población atea", 
        "Social", 
        "Porcentaje de la población no creyente", 
        "Porcentaje", 
        "%", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/demografia/religiones/espana",
         "Positivo",
         "Aumento del porcentaje de la población atea.",
         "Negativo",
         "Disminución del porcentaje de la población atea."),

        (331, "Población cristiana", 
        "Porcentaje de población cristiana", 
        "Social", 
        "Porcentaje de la población cuya religión es el cristianismo", 
        "Porcentaje", 
        "%", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/demografia/religiones/espana",
         "Positivo",
         "Aumento del porcentaje de la población cristiana.",
         "Negativo",
         "Disminución del porcentaje de la población cristiana."),

        (332, "Población musulmana", 
        "Porcentaje de población musulmana", 
        "Social", 
        "Porcentaje de la población cuya religión es el islam", 
        "Porcentaje", 
        "%", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/demografia/religiones/espana",
         "Positivo",
         "Aumento del porcentaje de la población musulmana.",
         "Negativo",
         "Disminución del porcentaje de la población musulmana."),

        (400, "Exportación de alta tecnología", 
        "Exportaciones de productos de alta tecnología", 
        "Tecnología", 
        "Valor de las exportaciones de productos de alta tecnología", 
        "Millones de euros", 
        "Mill.€", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCC58",
         "Positivo",
         "Aumento de las exportaciones de productos de alta tecnología.",
         "Negativo",
         "Disminución de las exportaciones de productos de alta tecnología."),

        (401, "Gastos I+D", 
        "Gastos internos en I+D", 
        "Tecnología", 
        "Cantidad de dinero destinado a I+D dentro de una organización, empresa o institución", 
        "Euros", 
        "€", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCC367",
         "Positivo",
         "Aumento de la cantidad de dinero destinado a I+D.",
         "Negativo",
         "Disminución de la cantidad de dinero destinado a I+D."),

        (402, "Importación de alta tecnología", 
        "Importaciones de productos de alta tecnología", 
        "Tecnología", 
        "Valor de las importaciones de productos de alta tecnología", 
        "Millones de euros", 
        "Mill.€", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCC60",
         "Positivo",
         "Aumento de las importaciones de productos de alta tecnología.",
         "Negativo",
         "Disminución de las importaciones de productos de alta tecnología."),

        (403, "Porcentaje de personas que compran por Internet", 
        "Porcentaje de personas (16 – 74 años) que compran por Internet", 
        "Tecnología", 
        "Porcentaje de personas entre 16 y 74 años que compran por Internet", 
        "Porcentaje", 
        "%", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCS49",
         "Positivo",
         "Aumento del porcentaje de personas que compran por Internet.",
         "Negativo",
         "Disminución del porcentaje de personas que compran por Internet."),

        (404, "Porcentaje de personas que usan Internet", 
        "Porcentaje de personas (16 – 74 años) que usan Internet", 
        "Tecnología", 
        "Porcentaje de personas entre 16 y 74 años que usan Internet", 
        "Porcentaje", 
        "%",
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCS42",
         "Positivo",
         "Aumento del porcentaje de personas que usan Internet.",
         "Negativo",
         "Disminución del porcentaje de personas que usan Internet."),

        (405, "Porcentaje de viviendas con ordenador", 
        "Porcentaje de viviendas con algún tipo de ordenador", 
        "Tecnología", 
        "Porcentaje de viviendas que tienen algún tipo de ordenador", 
        "Porcentaje", 
        "%", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCS2687",
         "Positivo",
         "Aumento del porcentaje de viviendas con ordenador.",
         "Negativo",
         "Disminución del porcentaje de viviendas con ordenador."),

        (406, "Producción de alta tecnología", 
        "Valor de la producción de bienes de alta tecnología", 
        "Tecnología", 
        "Valor del total de los bienes de alta tecnología producidos cada año", 
        "Millones de euros", 
        "Mill.€", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCC56",
         "Positivo",
         "Aumento del valor de los bienes de alta tecnología producidos.",
         "Negativo",
         "Disminución del valor de los bienes de alta tecnología producidos."),

        (500, "Consumo de energía", 
        "Consumo nacional de energía", 
        "Ecológico", 
        "Cantidad total de energía consumida en España cada año", 
        "Miles de terajulios", 
        "KTJ", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCEF391",
         "Negativo",
         "Aumento del consumo de energía.",
         "Positivo",
         "Disminución del consumo de energía."),

        (501, "Consumo energético de las empresas industriales", 
        "Consumo energético de las empresas industriales", 
        "Ecológico", 
        "Valor del consumo energético que tienen las empresas industriales cada año", 
        "Miles de euros", 
        "K€", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCI2",
         "Negativo",
         "Aumento del consumo de energía en empresas industriales.",
         "Positivo",
         "Disminución del consumo de energía en empresas industriales."),

        (502, "Consumo diario agua / Habitante", 
        "Consumo medio diario de agua por cada habitante", 
        "Ecológico", 
        "Volumen de agua consumido de media por cada habitante a diario", 
        "Litros por habitante", 
        "L / Hab", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCEF4",
         "Negativo",
         "Aumento del consumo de agua por habitante.",
         "Positivo",
         "Disminución del consumo de agua por habitante."),

        (503, "Consumo de agua del total de sectores económicos", 
        "Volumen de agua consumida por los sectores económicos", 
        "Ecológico", 
        "Volumen de agua consumido de media por los sectores económicos", 
        "Millones de litros", 
        "Mill.L", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCEF2",
         "Negativo",
         "Aumento del consumo de agua del total de sectores económicos.",
         "Positivo",
         "Disminución del consumo de agua del total de sectores económicos."),

        (504, "Coste del saneamiento de agua", 
        "Volumen de agua. Coste unitario del saneamiento", 
        "Ecológico", 
        "Coste unitario del saneamiento de cada metro cúbico de agua", 
        "Euros por metro cúbico", 
        "€ / m3", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCEF6",
         "Negativo",
         "Aumento del coste del saneamiento del agua.",
         "Positivo",
         "Disminución del coste del saneamiento del agua."),

        (505, "Coste del suministro de agua", 
        "Volumen de agua. Coste unitario del suministro", 
        "Ecológico", 
        "Coste unitario del suministro de cada metro cúbico de agua", 
        "Euros por metro cúbico", 
        "€ / m3", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCEF5",
         "Negativo",
         "Aumento del coste del suministro del agua.",
         "Positivo",
         "Disminución del coste del suministro del agua."),

        (506, "Intensidad energética", 
        "Intensidad energética", 
        "Ecológico", 
        "Cantidad de energía consumida para la realización de actividades económicas. Mide la eficiencia energética, es decir, si se necesita mayor energía, hay un menor rendimiento.", 
        "Miles de terajulios", 
        "KTJ", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCEF390",
         "Negativo",
         "Aumento de la cantidad de energía consumida por las actividades económicas, disminuyendo la eficiencia energética.",
         "Positivo",
         "Disminución de la cantidad de energía consumida por las actividades económicas, aumentando la eficiencia energética."),

        (507, "Emisiones a la atmósfera", 
        "Emisiones de gases de efecto invernadero (total de gases)", 
        "Ecológico", 
        "Cantidad total de todos los gases de efecto invernadero emitidos a la atmósfera", 
        "Miles de toneladas", 
        "KT", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCEF41",
         "Negativo",
         "Aumento de la cantidad de gases de efecto invernadero emitidos a la atmósfera.",
         "Positivo",
         "Disminución de la cantidad de gases de efecto invernadero emitidos a la atmósfera."),

        (508, "Emisiones de CO2", 
        "Emisión de gas. Dióxido de carbono", 
        "Ecológico", 
        "Cantidad total de dióxido de carbono (CO2) emitido a la atmósfera", 
        "Miles de toneladas", 
        "KT", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCEF42",
         "Negativo",
         "Aumento de la cantidad de dióxido de carbono (CO2) emitido a la atmósfera.",
         "Positivo",
         "Disminución de la cantidad de dióxido de carbono (CO2) emitido a la atmósfera."),

        (509, "Exportación de energía", 
        "Exportación de energía", 
        "Ecológico", 
        "Cantidad de energía exportada cada año", 
        "Miles de terajulios", 
        "KTJ", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCEF334",
         "Positivo",
         "Aumento de la cantidad de energía exportada.",
         "Negativo",
         "Disminución de la cantidad de energía exportada."),

        (510, "Gasto en gestión de aguas residuales", 
        "Gasto en gestión de aguas residuales", 
        "Ecológico", 
        "Cantidad destinada a la gestión de aguas residuales", 
        "Millones de euros", 
        "Mill.€", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCEF354",
         "Positivo",
         "Aumento de la cantidad de dinero destinado a la gestión de aguas residuales.",
         "Negativo",
         "Disminución de la cantidad de dinero destinado a la gestión de aguas residuales."),

        (511, "Gasto en gestión de residuos", 
        "Gasto en gestión de residuos", 
        "Ecológico", 
        "Cantidad destinada a la gestión de residuos", 
        "Millones de euros", 
        "Mill.€", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCEF353",
         "Positivo",
         "Aumento de la cantidad de dinero destinado a la gestión de residuos.",
         "Negativo",
         "Disminución de la cantidad de dinero destinado a la gestión de residuos."),

        (512, "Gasto en protección ambiental", 
        "Gasto industria protección ambiental. Gasto total", 
        "Ecológico", 
        "Cantidad destinada por parte de la industria a la protección ambiental", 
        "Miles de euros", 
        "K€", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCEF61",
         "Positivo",
         "Aumento de la cantidad de dinero destinado a la protección ambiental.",
         "Negativo",
         "Disminución de la cantidad de dinero destinado a la protección ambiental."),

        (513, "I+D medioambiental", 
        "Importe I+D medioambiental y otras actividades", 
        "Ecológico", 
        "Cantidad destinada a I+D (inversión y desarrollo) medioambiental y otras actividades", 
        "Millones de euros", 
        "Mill.€", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCEF356",
         "Positivo",
         "Aumento de la cantidad de dinero destinado a I+D medioambiental.",
         "Negativo",
         "Disminución de la cantidad de dinero destinado a I+D medioambiental."),

        (514, "Importación de energía", 
        "Importación de energía", 
        "Ecológico", 
        "Cantidad de energía importada cada año", 
        "Miles de terajulios", 
        "KTJ", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCEF333",
         "Positivo",
         "Aumento de la cantidad de energía exportada.",
         "Negativo",
         "Disminución de la cantidad de energía exportada."),

        (515, "Impuestos por contaminación y recursos", 
        "Impuestos ambientales por contaminación y recursos", 
        "Ecológico", 
        "Valor de los impuestos derivados a la contaminación y al consumo de recursos", 
        "Millones de euros", 
        "Mill.€", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCEF36",
         "Negativo",
         "Aumento del valor de los impuestos derivados a la contaminación y al consumo de recursos.",
         "Positivo",
         "Disminución del valor de los impuestos derivados a la contaminación y al consumo de recursos."),

        (516, "Impuestos por energía", 
        "Impuestos ambientales por energía", 
        "Ecológico", 
        "Valor de los impuestos derivados al consumo de energía", 
        "Millones de euros", 
        "Mill.€", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCEF34",
         "Negativo",
         "Aumento del valor de los impuestos derivados al consumo de energía.",
         "Positivo",
         "Disminución del valor de los impuestos derivados al consumo de energía."),

        (517, "Impuestos por transporte", 
        "Impuestos ambientales por transporte", 
        "Ecológico", 
        "Valor de los impuestos ambientales derivados al transporte", 
        "Millones de euros", 
        "Mill.€", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCEF35",
         "Negativo",
         "Aumento del valor de los impuestos ambientales derivados al transporte.",
         "Positivo",
         "Disminución del valor de los impuestos ambientales derivados al transporte."),

        (518, "Residuos generados en la economía", 
        "Residuos generados en la economía", 
        "Ecológico", 
        "Cantidad de residuos que genera la economía", 
        "Miles de toneladas", 
        "KT", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCEF340",
         "Negativo",
         "Aumento de la cantidad de residuos que genera la economía.",
         "Positivo",
         "Disminución de la cantidad de residuos que genera la economía."),

        (519, "Tratamiento final de residuos", 
        "Tratamiento final de residuos", 
        "Ecológico", 
        "Cantidad final de residuos tratados", 
        "Miles de toneladas", 
        "KT", 
        "Anual", 
        "ine", 
        "https://www.ine.es/consul/serie.do?d=true&s=DCEF343",
         "Positivo",
         "Aumento de la cantidad final de residuos tratados.",
         "Negativo",
         "Aumento de la cantidad final de residuos tratados."),

        (520, "Emisiones de CH4", 
        "Emisión de gas. Metano", 
        "Ecológico", 
        "Cantidad total de metano (CH4) emitido a la atmósfera", 
        "Millones de toneladas", 
        "Mill.T", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/energia-y-medio-ambiente/emisiones-ch4/espana",
         "Negativo",
         "Aumento de la cantidad de metano (CH4) emitido a la atmósfera.",
         "Positivo",
         "Disminución de la cantidad de metano (CH4) emitido a la atmósfera."),

        (521, "Producción de petróleo", 
        "Producción de petróleo", 
        "Ecológico", 
        "Cantidad de petróleo producido en el país", 
        "Miles de barriles al día", 
        "KBarril / Día", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/energia-y-medio-ambiente/petroleo/produccion/espana",
         "Positivo",
         "Aumento de la cantidad de petróleo producido en el país.",
         "Negativo",
         "Disminución de la cantidad de petróleo producido en el país."),

        (522, "Reservas de petróleo", 
        "Reservas de petróleo", 
        "Ecológico", 
        "Cantidad de petróleo que se puede recuperar con un costo factible", 
        "Millones de barriles", 
        "Mill.Barril", 
        "Anual", 
        "Datosmacro", 
        "https://datosmacro.expansion.com/energia-y-medio-ambiente/petroleo/reservas/espana",
         "Positivo",
         "Aumento de la cantidad de petróleo que se puede recuperar con un costo factible.",
         "Negativo",
         "Disminución de la cantidad de petróleo que se puede recuperar con un costo factible.")

                
    ]

    # Cargar todos los indicadores en la db
    cursor.executemany(
        """INSERT INTO indicadores (id, n_abv, nombre, dimension, descripcion, unidades, uds, periodicidad, fuente, url, siSube, subeExp, siBaja, bajaExp) 
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""", inds
    )

    # Cerrar conexión
    conex.commit()
    conex.close()



# Ejecutar
if __name__ == "__main__":
    crear_db()
